### ISSUE TITLE
gido is a bad name

### ISSUE THREAD

**Issue by ghost** [Cphrampus/git-functions#1]
I read it as guido every time. I propose that the name be changed to "cody". Its simple, and _elegant_

**Comment by Cphrampus** [comment]
The name has been updated to gitdo, which I feel a bit more accurately relates to the purpose, local aliasing or symlinks are always possible for using a different name. In addition, git extension files have been added, which should allow bypassing the use of the script directly for some common workflows.

**Comment by Cphrampus** [comment]
This has partly actually been done. For lack of a better name, the beta version, without the git prefix, has been named cody
